# Generated by Django 3.1.13 on 2021-10-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='provider',
            unique_together={('name', 'email')},
        ),
    ]
